baseURL = "/"
languageCode = "en-us"
title = "Patrick Makina"
publishDir = "_site"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Patrick Makina"
  description = "Graduate student in Mathematical Sciences at AIMS, Rwanda"
