baseURL = "/"
languageCode = "en-us"
title = "Patrick Makina"
theme = ""
publishDir = "_site"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Patrick Makina"
  description = "Graduate student in Mathematical Sciences at AIMS, Rwanda"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "CV"
  url = "/cv/"
  weight = 2

[[menu.main]]
  name = "Research"
  url = "/research/"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "/contacts/"
  weight = 4
