[build]
  command = "hugo"
  publish = "_site"

[build.environment]
  HUGO_VERSION = "0.121.2"

[context.production]
  command = "hugo"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
